max_width = 100                   # Maximum width of each line
tab_spaces = 4                    # Number of spaces per tab
indentation_style = "Auto"        # "Tabs", "Spaces" or "Auto"
newline_style = "Auto"            # "Unix", "Windows" or "Auto"
attr_value_brace_style = "WhenRequired"  # "Always", "AlwaysUnlessLit", "WhenRequired", or "Preserve"
macro_names = ["leptos::view", "view"]  # Macro names to format
closing_tag_style = "Preserve"    # "Preserve", "SelfClosing", or "NonSelfClosing"

# Attribute values can be formatted by custom formatters
[attr_values]
class = "Tailwind"                # Use Tailwind for `class` attributes
